server:
  port: 8091
spring:
  application:
    name: Micro01
  data:
    mongodb:
      database: NTTDATA_Botcamp32
      host: localhost
      port: 27017
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: 12345678
      